{
 "title": "Cpanel Mail Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(up{job=\"cpanel_mail_exporter\"}, instance)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary | External",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "email_user_stats{instance=\"$server\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Success", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 10 Domain",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(email_logs{sender=~\".*@.*\", type=\"success\", instance=\"$server\"}) by (domain))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Sender",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(email_logs{sender=~\".*@.*\", type=\"success\", instance=\"$server\"}) by (sender))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs By Success",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "email_logs{sender=~\".*@.*\", type=\"success\", instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top 10 Domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(email_logs{sender=~\".*@.*\", type=\"failure\", domain!=\"\", instance=\"$server\"}) by (domain))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Sender",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(email_logs{sender=~\".*@.*\",type=\"failure\", instance=\"$server\"}) by (sender))",
     "legendFormat": "{{ sender }} "
    }
   ]
  },
  {
   "title": "Logs by Failure",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "email_logs{type=\"failure\", sender=~\".*@.*\",instance=\"$server\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}